[package]
name = "vulkan-parse-derive-helper"
version = "0.1.0"
edition = "2021"
rust-version = "1.65"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = {version = "2.0", features = ["derive"]}
darling = "0.20"
